# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false
# Don't install anything that was released less than a week ago
npmMinimalAgeGate: 1w

approvedGitRepositories:
  - "**"

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.18.0.cjs
