import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { remark } from "remark";
import remarkGfm from "remark-gfm";
import type {
  Root,
  List,
  ListItem,
  PhrasingContent,
  Table,
  Paragraph,
  Heading,
} from "mdast";
import type { WgConfig } from "../../configSchema.ts";

const markdown = remark().use(remarkGfm);

export interface Attendee {
  name: string;
  github: string | null;
  org: string;
  location: string;
}

export interface Topic {
  process: boolean;
  title: string;
  duration: string | null;
  owner: string | null;
  subitems?: Subitem[];
}

export interface Subitem {
  title: string;
  subitems?: Subitem[];
}

export interface AgendaMeeting {
  title: string;
  start: string;
  end: string | null;
  attendees: Attendee[];
  topics: Topic[];
}

export interface AgendaDetails {
  meetings: AgendaMeeting[];
}

export async function getAgendaDetails(
  config: WgConfig,
  filter: { year?: string; month?: string; day?: string },
): Promise<AgendaDetails> {
  validateFilter(filter);
  const agendaDirectory = join(
    process.cwd(),
    config.repoSubpath ?? "",
    config.agendasFolder ?? "agendas",
  );
  const files = await markdownFiles(agendaDirectory);
  const meetings: AgendaMeeting[] = [];
  for (const file of files) {
    const contents = await readFile(file, "utf8");
    // A cancelled agenda may no longer have the normal date, attendee, or
    // agenda sections, so recognise it before trying to extract those fields.
    if (looksLikeItMightHaveBeenCancelled(contents)) continue;
    const date = getAgendaDate(contents);
    if (!date || !matchesFilter(agendaDay(file, agendaDirectory, date), filter))
      continue;
    const meeting = extractMeeting(contents, date);
    // A past agenda with fewer than two attendees generally represents a
    // meeting that did not take place.
    if (meeting.attendees.length < 2 && date <= new Date()) continue;
    meetings.push(meeting);
  }
  meetings.sort((a, b) => a.start.localeCompare(b.start));
  return { meetings };
}

function validateFilter(filter: {
  year?: string;
  month?: string;
  day?: string;
}) {
  const parts: Array<[string, string | undefined, number, number]> = [
    ["year", filter.year, 1, 9999],
    ["month", filter.month, 1, 12],
    ["day", filter.day, 1, 31],
  ];
  for (const [name, value, min, max] of parts) {
    if (
      value !== undefined &&
      (!/^\d+$/.test(value) || +value < min || +value > max)
    ) {
      throw new Error(`Invalid ${name} '${value}'`);
    }
  }
  if (filter.day !== undefined && filter.month === undefined) {
    throw new Error(`A day requires a month`);
  }
  if (filter.month !== undefined && filter.year === undefined) {
    throw new Error(`A month requires a year`);
  }
}

async function markdownFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory()
        ? markdownFiles(path)
        : entry.isFile() && entry.name.endsWith(".md")
          ? [path]
          : [];
    }),
  );
  return files.flat();
}

function matchesFilter(
  date: Date,
  filter: { year?: string; month?: string; day?: string },
) {
  return (
    (!filter.year || date.getUTCFullYear() === +filter.year) &&
    (!filter.month || date.getUTCMonth() + 1 === +filter.month) &&
    (!filter.day || date.getUTCDate() === +filter.day)
  );
}

// Prefer the date encoded in the generated agenda path. The timestamp in the
// timeanddate link is UTC, so it can belong to the preceding local calendar day.
function agendaDay(
  file: string,
  agendaDirectory: string,
  fallback: Date,
): Date {
  const match = /^(\d{4})\/(\d{2})-[^/]+\/(\d{2})-/.exec(
    relative(agendaDirectory, file),
  );
  return match
    ? new Date(Date.UTC(+match[1], +match[2] - 1, +match[3]))
    : fallback;
}

function extractMeeting(contents: string, start: Date): AgendaMeeting {
  const ast = markdown.parse(contents);
  const attendees = getAttendees(ast);
  const topics = getTopics(ast);
  return {
    title: getTitle(ast),
    start: start.toISOString(),
    end: getEnd(contents, start)?.toISOString() ?? null,
    attendees,
    topics,
  };
}

function getTitle(ast: Root): string {
  const heading = ast.children.find(
    (node): node is Heading => node.type === "heading" && node.depth === 1,
  );
  return heading ? text(heading.children).trim() : "";
}

/** Extract the attendee table, following the format generated by `agenda gen`. */
export function getAttendees(ast: Root): Attendee[] {
  const table = ast.children.find(
    (node): node is Table =>
      node.type === "table" && (node.align?.length ?? 0) >= 2,
  );
  if (!table) return [];
  const [header, ...rows] = table.children;
  if (!header) return [];
  const headings = header.children.map((cell) =>
    normalise(text(cell.children)),
  );
  return rows.map((row) => {
    const values = row.children.map((cell) => text(cell.children).trim());
    const value = (names: string[]) =>
      values[
        names.map((name) => headings.indexOf(name)).find((i) => i >= 0) ?? -1
      ] ?? "";
    return {
      name: value(["name"]),
      github: normaliseGitHubUsername(value(["github", "githubhandle"])),
      org: value(["organization", "organisation", "org"]),
      location: value(["location"]),
    };
  });
}

function normaliseGitHubUsername(value: string): string | null {
  const withoutPrefix = value.replace(/^https:\/\/github\.com\//i, "");
  const withoutAt = withoutPrefix.replace(/^@/, "");
  const firstInvalidCharacter = withoutAt.search(/[^a-z0-9-]/i);
  const username =
    firstInvalidCharacter === -1
      ? withoutAt
      : withoutAt.slice(0, firstInvalidCharacter);
  return username.replace(/[^a-z0-9]+$/i, "") || null;
}

function getTopics(ast: Root): Topic[] {
  for (let i = 0; i < ast.children.length - 1; i++) {
    const node = ast.children[i];
    if (
      node.type === "heading" &&
      normalise(text(node.children)) === "agenda"
    ) {
      for (const following of ast.children.slice(i + 1)) {
        if (following.type === "heading") return [];
        if (following.type === "list") return topicsFromList(following);
      }
    }
  }
  return [];
}

function topicsFromList(list: List): Topic[] {
  return list.children.map((item) => topicFromItem(item));
}

function topicFromItem(item: ListItem): Topic {
  const paragraph = item.children.find(
    (child): child is Paragraph => child.type === "paragraph",
  );
  const rawTitle = paragraph ? text(paragraph.children).trim() : "";
  const match = /\s*\(([^(),]+),\s*([^()]+)\)\s*$/.exec(rawTitle);
  const sublist = item.children.find(
    (child): child is List => child.type === "list",
  );
  const subitems = sublist ? subitemsFromList(sublist) : [];
  return {
    process: isNormalStuff(item),
    title: (match ? rawTitle.slice(0, match.index) : rawTitle).trim(),
    duration: match?.[1].trim() ?? null,
    owner: match?.[2].trim() ?? null,
    ...(subitems.length > 0 ? { subitems } : null),
  };
}

function subitemsFromList(list: List): Subitem[] {
  return list.children.map((item) => {
    const paragraph = item.children.find(
      (child): child is Paragraph => child.type === "paragraph",
    );
    const sublist = item.children.find(
      (child): child is List => child.type === "list",
    );
    const subitems = sublist ? subitemsFromList(sublist) : [];
    return {
      title: paragraph ? text(paragraph.children).trim() : "",
      ...(subitems.length > 0 ? { subitems } : null),
    };
  });
}

// The agenda generator adds these every meeting. Retain them, but distinguish
// them from discussion topics.
function isNormalStuff(item: ListItem): boolean {
  const paragraph = item.children.find(
    (child): child is Paragraph => child.type === "paragraph",
  );
  const firstChild = paragraph?.children[0];
  return (
    firstChild?.type === "text" &&
    /(Agree to Membership Agreement|Introduction of attendees|Determine volunteers for note|Review agenda|Review prior secondary|Review.*action items)/i.test(
      firstChild.value,
    )
  );
}

function text(nodes: PhrasingContent[]): string {
  return nodes
    .map((node) => {
      if (node.type === "text" || node.type === "inlineCode") return node.value;
      if ("children" in node) return text(node.children as PhrasingContent[]);
      if (node.type === "break") return "\n";
      return "";
    })
    .join("");
}

function normalise(value: string) {
  return value.toLowerCase().replace(/[^a-z]/g, "");
}

function getAgendaDate(contents: string): Date | null {
  const match =
    /https:\/\/www\.timeanddate\.com\/worldclock\/converter\.html\?iso=(\d{8}T\d{6})&/.exec(
      contents,
    );
  if (match) {
    const value = match[1];
    const date = new Date(
      `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}T${value.slice(9, 11)}:${value.slice(11, 13)}:${value.slice(13, 15)}Z`,
    );
    return Number.isNaN(+date) ? null : date;
  }
  // Older agenda templates used this timeanddate URL format.
  const oldMatch =
    /https:\/\/www\.timeanddate\.com\/worldclock\/meetingdetails\.html\?year=(\d+)&month=(\d+)&day=(\d+)&hour=(\d+)&min=(\d+)&/.exec(
      contents,
    );
  if (!oldMatch) return null;
  const [, year, month, day, hour, minute] = oldMatch;
  const date = new Date(
    `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}T${hour.padStart(2, "0")}:${minute.padStart(2, "0")}:00Z`,
  );
  return Number.isNaN(+date) ? null : date;
}

function looksLikeItMightHaveBeenCancelled(contents: string): boolean {
  return (
    /\bcancell?ed\b/i.test(contents) ||
    /\bmeeting has been moved\b/i.test(contents) ||
    /\bcall was moved\b/i.test(contents)
  );
}

function getEnd(contents: string, start: Date): Date | null {
  const match = /\*\*Date & Time\*\*:\s*\[([^\]]+)\]/.exec(contents);
  if (!match) return null;
  const times = [...match[1].matchAll(/(\d{1,2}):(\d{2})\s*(AM|PM)/gi)];
  if (times.length < 2) return null;
  const toMinutes = (time: RegExpMatchArray) =>
    ((+time[1] % 12) + (/pm/i.test(time[3]) ? 12 : 0)) * 60 + +time[2];
  const startMinutes = toMinutes(times[0]);
  let endMinutes = toMinutes(times[times.length - 1]);
  if (endMinutes <= startMinutes) endMinutes += 24 * 60;
  return new Date(+start + (endMinutes - startMinutes) * 60_000);
}

export function formatAgendaDetails(details: AgendaDetails): string {
  if (details.meetings.length === 0) return "No matching meetings.";
  return details.meetings
    .map((meeting) =>
      [
        ...(meeting.title ? [meeting.title] : []),
        `${meeting.start}${meeting.end ? ` – ${meeting.end}` : ""}`,
        "Attendees:",
        ...meeting.attendees.map(
          (attendee) =>
            `  - ${attendee.name}${attendee.github ? ` (${attendee.github})` : ""}${attendee.org ? `, ${attendee.org}` : ""}${attendee.location ? ` — ${attendee.location}` : ""}`,
        ),
        "Agenda:",
        ...formatTopics(meeting.topics, "  "),
      ].join("\n"),
    )
    .join("\n\n");
}

function formatTopics(topics: Topic[], indent: string): string[] {
  return topics
    .filter((topic) => !topic.process)
    .flatMap((topic) => [
      `${indent}- ${topic.process ? "[process] " : ""}${indentMultiline(topic.title, `${indent}  `)}${
        topic.duration
          ? ` (${indentMultiline(topic.duration, `${indent}  `)}${
              topic.owner
                ? `, ${indentMultiline(topic.owner, `${indent}  `)}`
                : ""
            })`
          : ""
      }`,
      ...formatSubitems(topic.subitems ?? [], `${indent}  `),
    ]);
}

function formatSubitems(subitems: Subitem[], indent: string): string[] {
  return subitems.flatMap((subitem) => [
    `${indent}- ${indentMultiline(subitem.title, `${indent}  `)}`,
    ...formatSubitems(subitem.subitems ?? [], `${indent}  `),
  ]);
}

/** Preserve item text in JSON; only indent its continuation lines for the CLI. */
function indentMultiline(value: string, continuationIndent: string): string {
  return value.replace(/\n/g, `\n${continuationIndent}`);
}
